name: Auto Sign-in Workflow

# 触发工作流的事件
on:
  schedule:
    # 设置定时触发规则，每天凌晨12点执行
    - cron: "*/5 * * * * ?"
  push:
    # 每次向 main 分支推送时触发
    branches:
      - main

jobs:
  auto-signin:
    runs-on: ubuntu-latest  # 使用最新版本的 Ubuntu 环境
    
    steps:

      # 执行自动签到脚本
      - name: Run auto sign-in script
        run: |
          python auto_checkin.py
